# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
