# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0002_auto_20170405_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(default=None),
        ),
    ]
