# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0003_auto_20170405_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
