# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0004_auto_20170405_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
