# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0006_auto_20170405_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default=None),
        ),
    ]
