# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_restful', '0007_auto_20170405_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
